title: mbmaciel
description: Desenvolvimento de sistemas web e aplicativos desde 2008
url: "https://blog.mbmaciel.com"

author:
  name: Mauricio Maciel
  email: me@mbmaciel.com

plugins:
  - jekyll-mentions
